### ISSUE TITLE
Use Topographical Maps as extra input

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#1]
As we primarily care about predicting where clouds are now and in the future, topographical information for the images could help, as clouds form differently around mountains or coasts potentially.

**Comment by JackKelly** [comment]
Good idea!  I _think_ some topographical information might be in the numerical weather prediction files, although I could definitely be wrong!  A while ago, Dan (Travers) found some topographical information for the UK to 3D-print 3D maps of the UK!

**Comment by jacobbieker** [comment]
Oh great! Yeah, I'll ask him about it. I found some from the [USGS](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-digital-elevation-shuttle-radar-topography-mission-srtm?qt-science_center_objects=0#qt-science_center_objects) that gives 30m resolution of the whole world. Just downlaoded it so need to mess around with it still though.

**Comment by JackKelly** [comment]
Awesome, amazing work!  I love that you're already finding lots of great data and playing with the data!

**Comment by jacobbieker** [comment]
MetNet includes this elevation data in their inputs, so it seems like it should help the model.
From the paper:
> The input features comprise the single MRMS radar image,
the 16 spectral bands of the GOES-16 satellite and additional real-valued features for the longitude,
latitude and elevation of each location in the patch as well as for the hour, day and month of the
input time Tx. The latter time features are tiled along the spatial dimensions of the input tensor
