### ISSUE TITLE
clarify development status

### ISSUE THREAD

**Issue by gerritholl** [openclimatefix/satflow#106]
The aims of the satflow package look promising and important.  It's good to see it's being actively developed.  Thanks!

Could you please clarify the development status using trove classifiers?  This would help potential users to tell if they're looking at something that can already be tested, or if the functionality is still incomplete at this stage.

**Comment by jacobbieker** [comment]
Thanks! And yes, I can add those classifiers a bit more, probably along with doing it for all the other nowcasting repos as well.

**Comment by jacobbieker** [comment]
69b1a227d760fe9b715a42873228d699f4cf1d29 should have closed that
