### ISSUE TITLE
  error: package directory 'satflow/data' does not exist

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/satflow#110]
**Describe the bug**
When first install satflow 
```
  error: package directory 'satflow/data' does not exist
```
this is done by using `pip isntall -e .`

**Comment by peterdudfield** [comment]
This is one branch `jacob/joint-model`

**Comment by jacobbieker** [comment]
Closed in https://github.com/openclimatefix/satflow/commit/3f89a026a32252a13a3f9d0d7ca5d17bd2446955
