### ISSUE TITLE
Add example data/benchmarks

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#30]
Add in some sample training data for others to be able to download and run some quick testing or benchmarks. Also record benchmarks for models.

**Comment by JackKelly** [comment]
At some point, we plan to publish the full (re-projected) EUMETSAT SEVIRI dataset on Google Cloud Public Datasets.  But, yeah, for now at least, it sounds like a great idea to include a sample dataset with the code :)

**Comment by jacobbieker** [comment]
#37 added a very small example data file for 20min of data on 2020/01/01.
