### ISSUE TITLE
Use only clouds for training

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#6]
One idea is to use just clouds, and not the ground for training and inference, so that the model can't get messed up by the ground. EUMETSAT does have binary cloud masks for the RSS, which should allow us to mask out the ground and only look at the movement of clouds. One potential issue is if new clouds develop or disappear, there could be useful information in the ground, or topology of the area that would be discarded, but we could try just using an elevation map as well to see. Related #1

**Comment by JackKelly** [comment]
Here's a GitHub discussion about cloud masks as training targets: https://github.com/openclimatefix/predict_pv_yield_2/issues/17  :)

**Comment by jacobbieker** [comment]
Thanks! Yeah, it looks like a ton of useful info there, for more refined/cloud-type segmentation masks the ideas of annotating some more images manually might be a good option a bit further down the line after I get this more setup.

**Comment by jacobbieker** [comment]
#39 now has training just on cloud masks sorta working, going from only cloud mask input to cloud mask output. The model does seem to be learning okay, still need to try CoordConv and other things to see if we can get better predictions.

**Comment by jacobbieker** [comment]
AFter trying it out some more and looking more at the masks, I think training on at least the binary cloud masks is maybe not the best way forward. Pixels can flip flop back and forth as the go above and below the threshold for being a 'cloud' and it seems like the PV models might also be extracting some information about the irradience from the satellite channels too. So mostly focusing on just predicting the satellite images from now. Might revist whenever I get the Optimal Cloud Product, which is a more fine grained mask #3 but for now, shelving the binary masks.
