### ISSUE TITLE
Add logging to Neptune

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#62]
Add logging to Neptune now that OCF has an account there. PR #56 added the configs, so it should be ready, but have to double check that.

**Comment by jacobbieker** [comment]
Doesn't seem to work for some reason still... Logging to ClearML for now

**Comment by jacobbieker** [comment]
https://github.com/openclimatefix/predict_pv_yield/blob/master/experiments/003_perceiver_processes_single_sat_image_then_rnn.py Might need to import the new NeptuneLogger for it to work

**Comment by jacobbieker** [comment]
Apparently the new logger is being added to PL in https://github.com/PyTorchLightning/pytorch-lightning/pull/6867 but it hasn't been merged yet. They also say the old one should still work? In any case, probably just add manually logging to Neptune for now

**Comment by kamil-kaczmarek** [comment]
hey @jacobbieker,

Kamil is here, Data Scientist from neptune.ai

I just came across this issue, I wonder if I can help you somehow with logging to neptune?

BTW: we already have neptune logger in the PytorchLightning project ( https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.loggers.neptune.html#pytorch_lightning.loggers.neptune.NeptuneLogger ). As you mentioned in your previous message, we now work on improved one.

**Comment by jacobbieker** [comment]
Hi @kamil-kaczmarek, thanks for the offer, but using your great docs, I believe I have it working now with the new API!

**Comment by kamil-kaczmarek** [comment]
Ok @jacobbieker sound great!

Feel free to reach out if you need sth.
