### ISSUE TITLE
Incorporate Radar Information

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#7]
Need to find where to get historical radar data, thinking that ground based radar would have better constant coverage of UK than satellites. Could add in as some more channels to the EUMETSAT image, or as an auxiliary image input, leaning more towards adding in as another channel(s).

**Comment by JackKelly** [comment]
Let me know if UK ground-based cloud-penetrating radar data isn't available and I'll ask my friendly contacts at the UK Met Office :)

**Comment by JackKelly** [comment]
Quick update on getting the 1km rainfall radar data from CEDA:

Turns out my login details still work for CEDA!  So we can access some CEDA data already (over HTTP or FTP), including getting more NWP data :) 

But [the 1km rainfall data](https://catalogue.ceda.ac.uk/uuid/27dd6ffba67f667a18c62de5c3456350) requires that I request access.  I'll request access later today.

**Comment by JackKelly** [comment]
I've requested access to the 1km rainfall radar data from CEDA (this data is just for the UK) :)

**Comment by jacobbieker** [comment]
Awesome, great! I'll see if I can find any radar data from Europe too

**Comment by JackKelly** [comment]
Woo - CEDA have granted us access to the UK rainfall radar data.  Links:

* Docs: https://catalogue.ceda.ac.uk/uuid/82adec1f896af6169112d09cc1174499
* Web access: http://data.ceda.ac.uk/badc/ukmo-nimrod
* FTP: ftp://ftp.ceda.ac.uk/badc/ukmo-nimrod

**Comment by jacobbieker** [comment]
Great! They also have 5km Europe data, so going to see if that works too

**Comment by jacobbieker** [comment]
TODO: use ```iris``` package to read in nimrod files and project to correct projection.

**Comment by jacobbieker** [comment]
Redundant now with https://github.com/openclimatefix/nowcasting_dataset/issues/80 so closing here
