### ISSUE TITLE
Switch to using Nowcasting Dataset

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/satflow#87]
Want to switch to using the more complete and less ad-hoc nowcasting dataset for training SatFlow now. Additional bonus of then just having a single data pipeline for SatFlow and PV yield.

**Comment by JackKelly** [comment]
Cool, sounds good!  I like the idea of us beginning to converge on using the same data; and sharing some code too.  Are you happy with the general approach that nowcasting_dataset takes?  i.e. pre-compute entire batches and save each batch to disk as NetCDF5 files?  The approach works well on cloud and should work well on a local filesystem too, although I haven't tested it locally yet!

**Comment by jacobbieker** [comment]
Yeah! I think it'll work fine, I did some pre-computing before and it worked well!
